### ISSUE TITLE
Update title

### ISSUE THREAD

**Issue by ben-rogerson** [lightyen/vscode-tailwindcss-twin#1]
Just trying out your extension and noticed the title hasn't been updated yet:

https://github.com/lightyen/vscode-tailwindcss-twin/blob/ce828040ae1e9e82ae6b5b410a1b2076a7e9db6b/package.json#L3

![image](https://user-images.githubusercontent.com/21288568/105154588-9bdb7580-5b59-11eb-8d9c-d5cfdca7cc21.png)

Also, is it possible to disable the links on the classes?
![image](https://user-images.githubusercontent.com/21288568/105155077-1b694480-5b5a-11eb-884c-b79d391d77a8.png)

**Comment by lightyen** [comment]
@ben-rogerson 

> Also, is it possible to disable the links on the classes?

In settings.json:
```json
{
  "tailwindcss.links": false
}
```

**Comment by ben-rogerson** [comment]
Great stuff, thanks!

**Comment by lightyen** [comment]
Update display name in v0.3.3
