### ISSUE TITLE
Show pixel <-> rem conversion

### ISSUE THREAD

**Issue by VictorLandim** [lightyen/vscode-tailwindcss-twin#10]
Hey there. Thanks for this awesome extension. It's been very useful.

One really nice feature from tailwindcss' vscode extension is that is shows the equivalent pixel value for a given rem.

For example:
![image](https://user-images.githubusercontent.com/5438965/113418409-cfc5e900-939b-11eb-98e3-0015f060975e.png)

Do you think that is a possibility?

Thanks again.

**Comment by lightyen** [comment]
It is possible and easy.
