### ISSUE TITLE
Error when using camelCase in short css

### ISSUE THREAD

**Issue by luknl** [lightyen/vscode-tailwindcss-twin#11]
Twin.macro have this short css feature (introduced with [2.2.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.2.0).  It lets you add css like this:
1) `tw="backgroundColor[red]"` (since [2.2.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.2.0))
2) `tw="background-color[red]"` (since [2.2.1](https://github.com/ben-rogerson/twin.macro/releases/tag/2.2.1))

However, when using option 1, it shows me an error (and it's working same as with option 2)
![image](https://user-images.githubusercontent.com/9930144/113904029-845f7080-97c9-11eb-8593-4ffa29c86d73.png)
![image](https://user-images.githubusercontent.com/9930144/113904127-a22cd580-97c9-11eb-98dc-d0cd178490e2.png)

Could it not show the error in case we want to use option 1?

**Comment by lightyen** [comment]
Got it. https://github.com/lightyen/vscode-tailwindcss-twin/commit/898ea103ba706c88c85be45faa4db1398480e51d
