### ISSUE TITLE
Support for twin.macro 2.5.0

### ISSUE THREAD

**Issue by luknl** [lightyen/vscode-tailwindcss-twin#13]
Hello, first, thanks for this awesome extension.
Second: is there any plan to support the latest release of twin.macro, [2.5.0](https://github.com/ben-rogerson/twin.macro/releases/tag/2.5.0)?

**Comment by lightyen** [comment]
I am going to implement those features, but twin.macro should cover all these test cases **first**: https://github.com/tailwindlabs/tailwindcss/blob/master/tests/jit/arbitrary-values.test.html

**Comment by ben-rogerson** [comment]
I'll make sure I cover all those cases in the next version 👍

**Comment by leohxj** [comment]
![image](https://user-images.githubusercontent.com/1506900/128463739-11d15285-9dd7-47af-a648-223ddae9affd.png)

Arbitrary values will get an error.

next version will support it ?
