### ISSUE TITLE
Errors when using variants and grid-template with names in short css syntax

### ISSUE THREAD

**Issue by ismasgrove** [lightyen/vscode-tailwindcss-twin#15]
Some recreations here and working alternatives for contrast: 

![error1](https://user-images.githubusercontent.com/45636192/131944948-11d40a66-aa64-4fa3-a772-76e40d497e34.jpg)
![error2](https://user-images.githubusercontent.com/45636192/131944953-24dfee0a-9db8-492d-9851-075b306287b4.jpg)
![error3](https://user-images.githubusercontent.com/45636192/131944955-73dd7e19-f7db-47b1-9f6f-ce0f9be7c874.jpg)
![error4](https://user-images.githubusercontent.com/45636192/131944958-15eb74f7-ecfa-4a6b-9be5-3f90a01414dd.jpg)

It's worth to say that similar code didn't report errors at all until version 0.9.0, so I'm guessing it has something to do with twin's latest JIT release introducing alternative syntax? Anyways, felt like I should report this.

**Comment by lightyen** [comment]
Fixed in 0.9.1
