### ISSUE TITLE
release on https://marketplace.visualstudio.com/ ?

### ISSUE THREAD

**Issue by rvion** [lightyen/vscode-tailwindcss-twin#2]
_Hi ! Thanks a lot for starting a new extension dedicated to react and `twin.macro`. I was about to start mine when I discovered your work. I linked your repository at the bottom of your [previous PR](https://github.com/tailwindlabs/tailwindcss-intellisense/pull/181)_

## Do you plan to release this on vscode store ? 

https://marketplace.visualstudio.com/

**Comment by lightyen** [comment]
This is my first time to write a vscode extension, I do this for fun.
You can discover it on vscode store **NOW**.
