### ISSUE TITLE
Code completion just stopped working! 😬 

### ISSUE THREAD

**Issue by mosesoak** [lightyen/vscode-tailwindcss-twin#20]
Bad news, I'm not sure if it was a VS Code update in the last few days or one of the extensions, but tailwind strings are no longer code hinting.

I also reported this to Ben at twin since I don't know what broke. This will slow our workflow considerably. What can we do to help figure this out?

Thanks!

**Comment by lightyen** [comment]
You can check the messge of console, go to "Output" -> "Tailwind Twin IntelliSence",
or provide a reproduce repo to me.
![image](https://user-images.githubusercontent.com/28860476/136121917-bbef078b-09fb-44e5-ae91-58cf61658457.png)

**Comment by mosesoak** [comment]
@lightyen Thank you that helped locate the problem. It was a helper function that was imported in our tailwind.config.js,

```js
const { withOpacity } = require('./src/utils/styles');

// in exported config:
      colors: {
        /* Add colors in r, g, b format in global.css */
        'brand-blue': withOpacity('--brand-blue'),
        ...
```

Moving the function into the file fixed the extension. The import wasn't a problem before but I don't know if it was a change on our end or VS Code that made it fail. Thanks again for your reply!
