### ISSUE TITLE
Styles not showing next to suggested className

### ISSUE THREAD

**Issue by jfarris587** [lightyen/vscode-tailwindcss-twin#26]
currently when typing `classNames` the styles do not show . The plugin is using default settings as installed:

![Screen Shot 2021-11-04 at 11 20 59 AM](https://user-images.githubusercontent.com/31263423/140351944-1a0a6d36-b494-44f8-aee4-e4725a99c65d.png)

as documented in how the plugin should work:

<img width="1186" alt="Screen Shot 2021-11-04 at 11 24 43 AM" src="https://user-images.githubusercontent.com/31263423/140351726-e5136ceb-1fab-4552-ba6a-20932966c2fd.png">

**Comment by lightyen** [comment]
Sorry, I can't understand your question, I don't see any problem in your screenshot. Can you provide more details?

**Comment by lightyen** [comment]
Close this, reopen it if you can provide more information.
