### ISSUE TITLE
Lagged cursor movement

### ISSUE THREAD

**Issue by ben-rogerson** [lightyen/vscode-tailwindcss-twin#29]
Hey there
@locona seems to be getting some lag while the extension is active, any ideas?

Here’s a post from [the discussion](https://github.com/ben-rogerson/twin.macro/discussions/227#discussioncomment-1743579)

> The reason why I don't use extention is that every time I make a typo, completion runs and slows things down.
> 
> As shown in the GIF below, the cursor movement  will be heavy.
> ![CleanShot 2021-12-12 at 13 40 49](https://user-images.githubusercontent.com/18649881/145700518-7253f694-a841-4475-844f-9af3f770943a.gif)
> 
> I've never done any extension development, so I don't know how to identify the cause.
> I hope you can help me.

**Comment by lightyen** [comment]
You are editing the **tailwind.config.js**. Because the extension need to create context via `tailwindcss` when a config changed.
In tailwind V2, It would take about 4 seconds (on my machine), and tailwind team has improved this in V3.

You can disable the extension until making things right:
 ```json5
{ "tailwindcss.enabled": false }
```

**Comment by locona** [comment]
@lightyen 
thanks.

The project for this GIF image is already tailwindcss v3.

Since tailwindcss.config.js is a configuration file, you can use
I verified it with the actual component file.

The results did not show any delay.

It seems that the `tailwindcss.config.js` file is special.

**Comment by lightyen** [comment]
Close due to inactivity.
