### ISSUE TITLE
Failed to load tailwind.config.js

### ISSUE THREAD

**Issue by r0skar** [lightyen/vscode-tailwindcss-twin#3]
Hei - Thanks for your work so far! I have just tried it and it works great out of the box. However, I noticed an issue when the custom `tailwind.config.js` file includes external imports and the plugin fails to resolve them. For example, I have a custom plugin (local) and my config file looks like this:

```js
const defaultTheme = require("tailwindcss/defaultTheme");
const myPlugin = require("./tailwind.plugin.custom.js");

module.exports = {/* ... */}
```

The TW plugin outputs
```
reload: /home/oskar/dev/next/tailwind.config.js
[Error] resolving config:
Error: Cannot find module './tailwind.plugin.spacing.js'
```

It works fine when I use an absolute path, which suggests the plugin tries to resolve paths relative to its install dir instead of the project root(?)

**Comment by lightyen** [comment]
I think it should work with relative path, and i have no issue in my side project.
Would you provide a minimal git repo that i can trace the bug?

**Comment by r0skar** [comment]
Sure thing; thanks for looking into this: https://github.com/r0skar/twin-ext-bug

**Comment by r0skar** [comment]
Oh I have now realized it works fine when the project folder is in my home dir. `/home/oskar/dev/` is a actually just a symlink to another folder on another disk. So, I guess the issues is with node and how it resolves those links... Its just weird that it never happened before and I am using the current folder structure for many years :thinking:

**Comment by r0skar** [comment]
I will try to figure out why it only happened with this project, but it seems this is more of an OS issue on my side and has nothing to do with this extension. Sorry for the noise :pray:

**Comment by lightyen** [comment]
I have found where it is, maybe it will be fixed next release.
[`00fcf1b`](https://github.com/lightyen/vscode-tailwindcss-twin/commit/00fcf1b1f133a97766e65cdacf5baf37b9e70c46#diff-0206f9c9ac89da1eef53a0b48b520d5c4710d9fe09f894be94f239fc48f4b94aR142-R144)
