### ISSUE TITLE
Tailwind V3 feedback

### ISSUE THREAD

**Issue by lightyen** [lightyen/vscode-tailwindcss-twin#30]
I am going to do some changes about tailwind v3 on [the branch](https://github.com/lightyen/vscode-tailwindcss-twin/tree/main) util twin v3 release.

If you have any requests, questions or something else, comment below.

~~Download [the preview version](https://github.com/lightyen/vscode-tailwindcss-twin/releases/download/v3.0.0-alpha.1/tailwindcss-intellisense-twin-3.0.0.vsix) to try v3 features.~~

---

2022/06/10 Update:
~~New prerelease version is published, download [link](https://github.com/lightyen/vscode-tailwindcss-twin/releases/download/v3.0.0-alpha.2/tailwindcss-intellisense-twin-3.0.0.vsix)~~

---

2022/06/15 Update:
~~New prerelease version is published, download [link](https://github.com/lightyen/vscode-tailwindcss-twin/releases/download/v3.0.0-rc.0/tailwindcss-intellisense-twin-3.0.0-rc.0.vsix)~~

---

2022/06/16 Update:
~~New prerelease version is published, download [link](https://github.com/lightyen/vscode-tailwindcss-twin/releases/download/v3.0.0-rc.1/tailwindcss-intellisense-twin-3.0.0-rc.1.vsix)~~

---

2022/06/25 Update:
~~New prerelease version is published, download [ver. 3.0.0-rc.4](https://github.com/lightyen/vscode-tailwindcss-twin/releases/download/v3.0.0-rc.4/tailwindcss-intellisense-twin-3.0.0-rc.4.vsix)~~

---

2022/07/26 Update:

~~New prerelease version is published, download [ver. 3.0.0-rc.5](https://github.com/lightyen/vscode-tailwindcss-twin/releases/download/v3.0.0-rc.5/tailwindcss-intellisense-twin-3.0.0-rc.5.vsix)~~

---

2022/09/01 Update:
~~New prerelease version is published, download [ver. 3.0.0-rc.6](https://github.com/lightyen/vscode-tailwindcss-twin/releases/download/v3.0.0-rc.6/tailwindcss-intellisense-twin-3.0.0-rc.6.vsix)~~

**Comment by u3u** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/20062482/173808654-46373fe6-35ec-45e2-a665-bdaf3288995b.png">
 
Update to [3.0.0-rc.0](https://github.com/lightyen/vscode-tailwindcss-twin/releases/tag/v3.0.0-rc.0) will report an error when using like `text-black/[.02]`
By the way, can you hint out the alpha value like this?

<img width="783" alt="image" src="https://user-images.githubusercontent.com/20062482/173809539-70daef37-18ad-478f-868c-c4a2940619d1.png">

**Comment by u3u** [comment]
Nested groupings can break syntax highlighting

<img width="469" alt="image" src="https://user-images.githubusercontent.com/20062482/173810928-50f1518d-b75f-4c47-bdfb-8635d678ab30.png">

Or using the grouping syntax on a single line in `styled.div` will also break the highlighting

<img width="814" alt="image" src="https://user-images.githubusercontent.com/20062482/173811048-2f75cbef-4da6-496f-ba01-e8b7c43aaf85.png">

But no problem with multiple lines

<img width="583" alt="image" src="https://user-images.githubusercontent.com/20062482/173811151-49263527-237a-4d2c-94d7-8507c2fe51b8.png">

**Comment by lightyen** [comment]
> Update to [3.0.0-rc.0](https://github.com/lightyen/vscode-tailwindcss-twin/releases/tag/v3.0.0-rc.0) will report an error when using like `bg-black/[.02]` By the way, can you hint out the alpha value like this?
> 
I will fix/add these in next version.


> Nested groupings can break syntax highlighting
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/20062482/173810928-50f1518d-b75f-4c47-bdfb-8635d678ab30.png">
> 
The bug comes from [vscode-styled-components](https://github.com/styled-components/vscode-styled-components) at this [line](https://github.com/styled-components/vscode-styled-components/blob/cfc992d93b16ddd0bc77b47c469d94e5892b2656/syntaxes/styled-components.json#L78), it matches the string pattern:
```
))`
```
I not sure what I can do.

Workaround: Just disable vscode-styled-components or add some characters(like space) before the backtick to break vscode-styled-components's regex rules.

**Comment by u3u** [comment]
Thank you so much for the survey!

**Comment by berry95** [comment]
Is there a reason why you don't release it on Marketplace?

**Comment by mosesoak** [comment]
@lightyen Hi, I just upgraded a project to use twin beta rc5 (`3.0.0-rc.5`) and have reinstalled your VS Code plugin, and restarted VS Code after doing so, but am getting highlight errors on the newer custom properties syntax:

![image](https://user-images.githubusercontent.com/24345/197584199-d41efae9-fc1b-4ab5-b3ac-da3c3c7bfa61.png)

Is that syntax supported yet? I'm not sure when @ben-rogerson is planning on rolling out V3 but supporting this syntax would be helpful for our team! Thanks for your excellent work!

**Comment by lightyen** [comment]
> Is that syntax supported yet?

@mosesoak That syntax is supported already. Did you have installed `tailwindcss-intellisense-twin-3.0.0-rc.6.vsix`? The source id should be "twin"(not "tw").

**Comment by lightyen** [comment]
[vscode-tailwindcss-twin v3.0.0](https://github.com/lightyen/vscode-tailwindcss-twin) has been published and it may be the last version I maintained.

I switched my projects to [twobj](https://github.com/lightyen/twobj) and not use `babel-plugin-macros` anymore.

**Comment by mosesoak** [comment]
Thanks -- this is great, works perfectly so far!

So, you mean that you've written your own utility and aren't using twin.macro at all any more? Does yours support emotion styled components?
