### ISSUE TITLE
How to format on save (like it works with all styled.<tag> functions)?

### ISSUE THREAD

**Issue by mkvlrn** [lightyen/vscode-tailwindcss-twin#31]
I may be missing something really obvious but is there a way to make vscode auto format the template string as css just like it does with styled-components or @emotion/styled?

I'm getting syntax highlighting and auto completion and I have `vscode-styled-components` extension installed as well.

**Comment by lightyen** [comment]
Formatting is not the main feature in this extension, people usually choose `prettier` when doing document formatting.
But I don't know how to write a prettier plugin about embedded lang, it is [hard coded](https://github.com/prettier/prettier/blob/d13feed42b6478710bebbcd3225ab6f203a914c1/src/language-js/embed.js).

**Comment by lightyen** [comment]
Close due to inactivity.
