### ISSUE TITLE
Doubled suggestions when using within a vscode-workspace

### ISSUE THREAD

**Issue by wottpal** [lightyen/vscode-tailwindcss-twin#37]
When I open a vscode workspace of a monorepo (`project.code-workspace`) file it successfully locates my config (`packages/frontend/tailwind.config.js`) but all suggestions are shown twice. If I open the same monorepo just by its folder the suggestions are back to normal.

<img width="383" alt="Screen Shot 2022-06-08 at 11 21 05" src="https://user-images.githubusercontent.com/3930150/172581160-fc544ae0-26c3-456b-b72c-9d36c1af353e.png">

Sample `project.code-workspace`:
```json
{
  "folders": [
    {
      "name": "_ROOT",
      "path": "../"
    },
    {
      "name": "Frontend",
      "path": "../packages/frontend"
    }
  ],
  "settings": {
    "files.exclude": {
      "**/node_modules/": true,
      "**/package-lock.json": true,
      "**/yarn.lock": true,
      "**/yarn-error.log": true,
      "**/.yarn": true,
    },
  }
}
```

Little tip: When you open a `code-workspace`-file in VSCode a button in the lower right appears where you can switch to workspace-mode :)

PS: I also tried with v3.0.0

**Comment by lightyen** [comment]
Updated in https://github.com/lightyen/vscode-tailwindcss-twin/issues/30
