### ISSUE TITLE
Specify config location

### ISSUE THREAD

**Issue by migueloller** [lightyen/vscode-tailwindcss-twin#4]
Would it be possible to add a configuration setting so that the location of the Tailwind configuration can be customized?

**Comment by lightyen** [comment]
The feature is not implemented because i don't think it is a good idea. Why do you need this?

**Comment by migueloller** [comment]
Because we have a monorepo so the project that uses Tailwind is not located at the root of the workspace.

**Comment by lightyen** [comment]
I treat each `tailwind.config.js` as a sub root, monorepo architecture is ok. (I also tested with [twin.example](https://github.com/ben-rogerson/twin.examples))

**Comment by migueloller** [comment]
Interesting. I was running into an issue where the configuration was not being found. I’ll report back if I find a reliable way to reproduce.
