### ISSUE TITLE
Add source action for converting `tw` ↔ `css` attribute syntax

### ISSUE THREAD

**Issue by wottpal** [lightyen/vscode-tailwindcss-twin#41]
gm @lightyen, i've seen that you stop actively working on this plugin (which is fine, what you've already built here is amazing!)

i was thinking about doing a pr about the issue i'm going to describe here, but i first wanted to hear your opinion. and maybe you can point me to some docs about how to add a "source action" to a vscode extension (never done that before and didn't find it after a quick googling.

**the problem:** i often find myself changing the syntax from something like …

```jsx
<div tw="text-white">
```

to this …

```jsx
<div css={[
  tw`text-white`,
  // isError && tw`text-red-500`
]}>
```

to be able to do conditional style changes (see the example in the comment).

this conversion, though, is very tedious (many special characters involved etc.), and sometimes i even need to go back and forth, which makes this even more unbearable. 

**the (potential) solution:** adding a source action with this plugin that allows me to convert one syntax to the other and vice-versa quickly.

what do you think?

**Comment by lightyen** [comment]
In this situation, i will use `tw` and `css` attr both in my code:
```jsx
<div 
  tw="text-primary"
  css={[
    invalid && tw`text-error`,
  ]}
/>
```

**Comment by wottpal** [comment]
🤯 haha so simple, somehow i've assumed that only one of those two attributes works at a time...
ok then i only need to add a vscode snippet for css={[tw`$1`]} and t'm good to go :)
ty, can be closed.
