### ISSUE TITLE
release on https://open-vsx.org/ ?

### ISSUE THREAD

**Issue by rvion** [lightyen/vscode-tailwindcss-twin#5]
Hi again, I'm trying to setup a web-based vscode instance.

Most web-based vscode variants ([A](https://github.com/cdr/code-server), [B](https://www.gitpod.io/), [C](https://theia-ide.org/), ...) are converging on https://open-vsx.org/ for their extension store 

Could you also release it on this store ?

( just found [this issue](https://github.com/cdr/code-server/issues/2733) on code-server btw, your extension is one of the few that was already requested )

**Comment by rvion** [comment]
edit: I actually won't use it. I've found an other way to avoid needing web-based vscodes
I leave this open so you can decide whether to close or not

**Comment by lightyen** [comment]
- https://open-vsx.org/extension/lightyen/tailwindcss-intellisense-twin
- https://github.com/lightyen/vscode-tailwindcss-twin/commit/74606148e048f9ad205e7358a4c52881dbcf4bb2

**Comment by rvion** [comment]
thanks ! 
Have you thought about adding a donation link / setting-up github sponsors ?

**Comment by lightyen** [comment]
> thanks !
> Have you thought about adding a donation link / setting-up github sponsors ?

No plan.
