### ISSUE TITLE
Support babel plugin twin

### ISSUE THREAD

**Issue by luknl** [lightyen/vscode-tailwindcss-twin#6]
Hi, first thanks for the great plugin, so useful!

Twin.macro just released a [babel plugin](https://github.com/ben-rogerson/babel-plugin-twin) that make the `import "twin.macro"` not mandatory anymore.
However, auto-completion from this plugin doesn't work when we remove this import line.

Is there a way for those 2 plugins to be compatible?

Thanks!

**Comment by lightyen** [comment]
I will add a vscode setting to disable import checking in the next version.
> But I still think that is not good without import "twin.macro" module when people didn't know what happen.

**Comment by luknl** [comment]
Ok great thanks!

**Comment by ben-rogerson** [comment]
> I will add a vscode setting to disable import checking in the next version.

Sweet - love your work @lightyen!

> But I still think that is not good without import "twin.macro" module when people didn't know what happen.

I originally thought the same thing, but now after using it on a few projects I'm really enjoying it. It's an "opt-in" plugin, so twin-core stays as declarative as it has been.

**Comment by lightyen** [comment]
Use this setting in v0.7.0:
```json5
{
  "tailwindcss.jsxPropImportChecking": false
}
```

**Comment by luknl** [comment]
Works perfectly, thanks :+1:
