### ISSUE TITLE
x is conflicted on property: y

### ISSUE THREAD

**Issue by giacomorebonato** [lightyen/vscode-tailwindcss-twin#8]
Hello everyone and thanks for this extension :)
It's unclear to me what's happening here in this example and I need all these 3 classes to achieve what I intend to.

<img width="874" alt="Screenshot 2021-03-17 at 07 52 50" src="https://user-images.githubusercontent.com/630796/111427141-ee6a8580-86f5-11eb-8b15-b72d0083c623.png">

Do you know what's going on?

**Comment by lightyen** [comment]
This is what I expected behavior, because `transition` already has easing function and duration time.
You can add *!important* with trailing bang `!` behind `ease-in` and `duration-100`.

**Comment by giacomorebonato** [comment]
Thanks.

**Comment by giacomorebonato** [comment]
Picking examples straight from Tailwind website lead me to this warning.
https://tailwindcss.com/docs/transition-property

Could you clarify expected behaviour? (genuinely asking, I am not sure that I am getting this right).
If I write tw\`transition duration-500\` I expect `duration-500` to be picked up and overwrite the one on `transition`.
Isn't this what's happening? I am not very comfortable in using "!important" for this purpose.

**Comment by lightyen** [comment]
I don't think **overwriting** between utilities is good. If you don't like it, you can use this setting:
```json5
{
  "tailwindcss.diagnostics": {
    "conflict": "loose"
  }
}
```
> This will check the confliction only if all css property are matched.

**Comment by giacomorebonato** [comment]
Thanks for the settings information. I didn't know about that.
